name: CI/CD

on: 
  workflow_dispatch:
  push:
    branches: [main develop]
  pull_request: 
    branches: [main]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: "postgresql://user:password@localhost:5432/db"
      JWT_SECRET: "ci-secret"
      JWT_RESET_SECRET: "ci-reset-secret"
      NEXT_PUBLIC_API_URL: "http://localhost:4000"

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Instalar dependências
        run: npm ci

      - name: Rodar testes (Jest)
        run: npm test

      - name: lint (EsLint)
        run: npm run lint

      - name: Checar tipos (TypeScript)
        run: npx tsc --noEmit

      - name: Build
        run: npm run build