name: CI/CD

on: 
  workflow_dispatch:
  push:
    branches: [main develop]
  pull_request: 
    branches: [main]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        ports: 
          - 5432:5432
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: db
        options: >-
          --health-cmd="pg_isready -U user -d db"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    env:
      NODE_ENV: test
      CI: "true"
      DATABASE_URL:  ${{ secrets.DATABASE_URL }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      JWT_RESET_SECRET: ${{ secrets.JWT_RESET_SECRET }}
      NEXT_PUBLIC_API_URL: "http://localhost:4000"
      FRONTEND_URL: http://localhost:3000

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Instalar dependências
        run: npm ci

      - name: Gerar Prisma Client
        run: npx prisma generate

      - name: Esperar banco estabilizar   
        env:
          PGPASSWORD: password
        run: |
          for i in {1..60}; do
            if pg_isready -h localhost -p 5432 -U user >/dev/null 2>&1; then
              echo "Postgres está aceitando conexões."
              exit 0
            fi
            echo "Tentativa $i: Postgres ainda não está pronto..."
            sleep 2
          done
          echo "Postgres não ficou pronto após 120 segundos."
          exit 1

      - name: Rodar migrations
        run: npx prisma migrate deploy

      - name: Rodar testes (Jest)
        run: npm test -- --runInBand --detectOpenHandles --forceExit

      - name: lint (EsLint)
        run: npm run lint

      - name: Checar tipos (TypeScript)
        run: npx tsc --noEmit

      - name: Build
        run: npm run build